services:
  bot:
    image: ghcr.io/holedaemon/bot2:latest
    container_name: "bot2_bot"
    command: [ "bot" ]
    restart: unless-stopped
    environment:
      BOT2_BOT_ADMINS: "${BOT2_BOT_ADMINS}"
      BOT2_BOT_TOKEN: "${BOT2_BOT_TOKEN}"
      BOT2_BOT_TOPSTER_ADDR: "${BOT2_BOT_TOPSTER_ADDR}"
      BOT2_BOT_SITE_ADDR: "${BOT2_BOT_SITE_ADDR}"
      BOT2_BOT_LOGGING_WEBHOOK_URL: "${BOT2_BOT_LOGGING_WEBHOOK_URL}"
      BOT2_BOT_FEEDBACK_WEBHOOK_URL: "${BOT2_BOT_FEEDBACK_WEBHOOK_URL}"
      BOT2_BOT_STEAM_API_KEY: "${BOT2_BOT_STEAM_API_KEY}"
      BOT2_DB_MIGRATE: "${BOT2_DB_MIGRATE}"
      BOT2_DEBUG: "${BOT2_DEBUG}"
      BOT2_DB_DSN: "${BOT2_DB_DSN}"
    networks:
      - bot2

  web:
    image: ghcr.io/holedaemon/bot2:latest
    container_name: "bot2_web"
    command: [ "web" ]
    restart: unless-stopped
    environment:
      BOT2_WEB_ADDR: "${BOT2_WEB_ADDR}"
      BOT2_WEB_ADMINS: "${BOT2_WEB_ADMINS}"
      BOT2_WEB_OAUTH2_CLIENT_ID: "${BOT2_WEB_OAUTH2_CLIENT_ID}"
      BOT2_WEB_OAUTH2_CLIENT_SECRET: "${BOT2_WEB_OAUTH2_CLIENT_SECRET}"
      BOT2_WEB_OAUTH2_SCOPES: "${BOT2_WEB_OAUTH2_SCOPES}"
      BOT2_WEB_OAUTH2_REDIRECT_URL: "${BOT2_WEB_OAUTH2_REDIRECT_URL}"
      BOT2_DB_DSN: "${BOT2_DB_DSN}"
      BOT2_DB_MIGRATE: "false"
    networks:
      - bot2
      - caddy

  postgres:
    image: postgres:17
    container_name: "bot2_postgres"
    restart: unless-stopped
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    volumes:
      - "/var/opt/slapshit/bot2/database:/var/lib/postgresql/data"
    networks:
      - bot2

  gopster:
    image: ghcr.io/holedaemon/microgopster:latest
    container_name: "bot2_gopster"
    restart: unless-stopped
    environment:
      MICROGOPSTER_ADDR: "${MICROGOPSTER_ADDR}"
      MICROGOPSTER_LAST_API_KEY: "${MICROGOPSTER_LAST_API_KEY}"
    networks:
      - caddy

networks:
  bot2:
    external: true
  caddy:
    external: true
