services:
  caddy:
    image: caddy:2
    container_name: caddy
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    environment:
      SEEDHOST_ACCESS_USERNAME: '${SEEDHOST_ACCESS_USERNAME}'
      SEEDHOST_ACCESS_PASSWORD: '${SEEDHOST_ACCESS_PASSWORD}'
      SEEDHOST_DELUGE_PASSWORD: '${SEEDHOST_DELUGE_PASSWORD}'
      SEEDHOST_RADARR_PASSWORD: '${SEEDHOST_RADARR_PASSWORD}'
      SEEDHOST_PROWLARR_PASSWORD: '${SEEDHOST_PROWLARR_PASSWORD}'
      SEEDHOST_SONARR_PASSWORD: '${SEEDHOST_SONARR_PASSWORD}'
      SEEDHOST_SABNZBD_PASSWORD: '${SEEDHOST_SABNZBD_PASSWORD}'
      JAUNTY_DISCORD_SLUG: "${JAUNTY_DISCORD_SLUG}"
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - "/srv/www:/srv"
      - "./config:/etc/caddy"
      - "data:/data"
      - "config:/config"
    networks:
      - caddy

volumes:
  data:
  config:

networks:
  caddy:
    external: true
