services:
  forgejo:
    image: codeberg.org/forgejo/forgejo:14
    container_name: forgejo
    restart: unless-stopped
    command: [ "forgejo", "web", "--config", "/etc/forgejo/config.ini" ]
    environment:
      USER_UID: ${USER_UID}
      USER_GID: ${USER_GID}

      FORGEJO__database__PASSWD: ${FORGEJO__database__PASSWD}
      FORGEJO__security__SECRET_KEY: ${FORGEJO__security__SECRET_KEY}
      FORGEJO__security__INTERNAL_TOKEN: ${FORGEJO__security__INTERNAL_TOKEN}
    ports:
      - 2222:2222
    volumes:
      - ./config:/etc/forgejo
      - /home/git/.local/share/forgejo:/data
      - /etc/localtime:/etc/localtime:ro
    networks:
      - forgejo
      - caddy

  database:
    image: postgres:18
    container_name: forgejo_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - /var/opt/slapshit/forgejo/database:/var/lib/postgresql
    networks:
      - forgejo

networks:
  forgejo:
    external: true

  caddy:
    external: true
