services:
  forgejo:
    image: codeberg.org/forgejo/forgejo:14-rootless
    container_name: forgejo
    restart: unless-stopped
    user: 1000:1000
    cap_add:
      - NET_BIND_SERVICE
    environment:
      USER_UID: 1000
      USER_GID: 1000
      FORGEJO_CUSTOM: /etc/gitea
      FORGEJO__database__PASSWD: ${FORGEJO__database__PASSWD}
    ports:
      - "22:2222"
    volumes:
      - ./config:/etc/gitea
      - /var/opt/slapshit/forgejo/data:/var/lib/gitea
      - /etc/localtime:/etc/localtime:ro
    networks:
      - caddy
      - forgejo
    depends_on:
      - database

  database:
    image: postgres:18
    container_name: forgejo_database
    restart: unless-stopped
    environment:
      POSTGRES_USER: forgejo
      POSTGRES_PASSWORD: ${FORGEJO__database__PASSWD}
      POSTGRES_DB: forgejo
    volumes:
      - /var/opt/slapshit/forgejo/database:/var/lib/postgresql/data
    networks:
      - forgejo

networks:
  caddy:
    external: true

  forgejo:
    external: true
