APP_NAME = Slapshit Apocrypha
APP_SLOGAN = Code even Jesus wouldn't touch!

RUN_USER = git
RUN_MODE = prod

[server]
;; prefer http since we're proxying via caddy
PROTOCOL = http

DOMAIN = slapshit.net

HTTP_PORT = 8080

START_SSH_SERVER = false
SSH_CREATE_AUTHORIZED_KEYS_FILE = false

[database]

DB_TYPE = postgres
HOST = forgejo_postgres
NAME = gitea
USER = forgejo
SSL_MODE = disable

[service]

DISABLE_REGISTRATION = true
DISABLE_STARS = true
DEFAULT_BRANCH = trunk

[other]

SHOW_FOOTER_VERSION = false
SHOW_FOOTER_TEMPLATE_LOAD_TIME = false
SHOW_FOOTER_POWERED_BY = false
